site_name:           ClinicalTrialSampleSize
site_description:    Calculate Sample Size/Power for Clinical Trials
site_author:         Zhenning Yu
site_url:            http://contatp.github.io/ClinicalTrialSampleSize.jl
theme:               cinder

repo_url:            https://github.com/ContaTP/ClinicalTrialSampleSize.jl

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Usage:
  - Usage: man/usage.md
- Index:
  - Command: man/command.md
